# Generated by Django 3.2.8 on 2021-10-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop_price',
            field=models.FloatField(null=True),
        ),
    ]
