# Generated by Django 3.2.8 on 2021-11-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Out For Delivery'), (2, 'Delievred')], default=0, null=True),
        ),
    ]
