# Generated by Django 3.2.8 on 2021-11-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibilty',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
