# Generated by Django 3.2.8 on 2021-11-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211121_0621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='transaction_id',
        ),
    ]
