# Generated by Django 3.2.8 on 2021-11-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_order_id_order_transaction_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created']},
        ),
    ]
