# Generated by Django 3.2.8 on 2021-11-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_created']},
        ),
    ]
